"""init

Revision ID: bb2e2ce852df
Revises: 
Create Date: 2026-04-10 17:11:08.722735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2e2ce852df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) Создаём таблицу webhook_config
    op.create_table(
        'webhook_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('webhook_id', sa.String(), nullable=False),
        sa.Column('secret', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=True),
        sa.Column('team_id', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('telegram_chats')
    op.add_column(
        'subscriptions',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=True,
            server_default=sa.text('false'),
        )
    )
    op.alter_column(
        'subscriptions',
        'is_active',
        nullable=False,
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_active')
    op.create_table('telegram_chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tg_chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('telegram_chats_pkey')),
    sa.UniqueConstraint('tg_chat_id', name=op.f('telegram_chats_tg_chat_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('webhook_config')
    # ### end Alembic commands ###
